version: '3'
services:
  influxdb:
    container_name: safran-server-influx
    image: influxdb:latest
    environment:
      INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
      INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - ./data:/var/lib/influxdb
  #chronograf:
  #  container_name: safran-server-chrono
  #  image: chronograf:latest
  #  ports:
  #    - "8889:8888"
  #  links:
  #    - influxdb
  #grafana:
  #  container_name: safran-server-grafana
  #  image: grafana/grafana:latest
  #  ports:
  #    - "3000:3000"
  #  links:
  #    - influxdb
  #  volumes:
  #    - ./data_grafana:/var/lib/grafana
volumes:
  data:
  #data_grafana:
